[versions]
kotlin = "2.0.0"
kotlin_wrappers_js = "1.0.0-pre.774"

[libraries]
kotlin_wrappers_js = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-js", version.ref = "kotlin_wrappers_js" }

[plugins]
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
